services:
  backend:
    build:
      context: ./backend
    container_name: tunelog-backend
    restart: always 
    tty: true 
    stdin_open: true
    volumes:
      - ./data:/app/data
      - ./backend/logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - FORCE_COLOR=1
      - TERM=xterm-256color
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "4534:4534"

  frontend:
    build:
      context: ./frontend
    container_name: tunelog-frontend
    restart: always 
    tty: true
    environment:
      VITE_ALLOWED_HOSTS: tunelog.${MY_DOMAIN}
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend
